# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage
import requests


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.location_selection = QtWidgets.QComboBox(self.centralwidget)
        self.location_selection.setGeometry(QtCore.QRect(280, 10, 100, 22))
        self.location_selection.setObjectName("location_selection")
        self.location_selection.addItem("")
        self.location_selection.addItem("")
        self.location_selection.addItem("")
        self.location_selection.addItem("")
        self.location_selection.addItem("")
        self.location_label = QtWidgets.QLabel(self.centralwidget)
        self.location_label.setGeometry(QtCore.QRect(230, 10, 69, 22))
        self.location_label.setObjectName("location_label")
        self.location_label.setText("Location: ")
        self.fahrenheit_label = QtWidgets.QLabel(self.centralwidget)
        self.fahrenheit_label.setGeometry(QtCore.QRect(490, 100, 50, 50))
        self.fahrenheit_label.setObjectName("fahrenheit_label")
        self.fahrenheit_label.setText("Degrees F")
        self.f_temp = QtWidgets.QLabel(self.centralwidget)
        self.f_temp.setGeometry(QtCore.QRect(450, 100, 50, 50))
        self.f_temp.setObjectName("f_temp")

        self.c_temp = QtWidgets.QLabel(self.centralwidget)
        self.c_temp.setGeometry(QtCore.QRect(450, 120, 50, 50))
        self.c_temp.setObjectName("c_temp")

        self.celcius_label = QtWidgets.QLabel(self.centralwidget)
        self.celcius_label.setGeometry(QtCore.QRect(490, 120, 50, 50))
        self.celcius_label.setObjectName(("celcius_label"))
        self.celcius_label.setText("Degrees C")
        self.get_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_button.setGeometry(QtCore.QRect(280, 335, 72, 22))
        self.get_button.setObjectName("get_button")
        self.get_button.setText('Get Weather')
        self.weather_icon_label = QtWidgets.QLabel(self.centralwidget)
        self.weather_icon_label.setGeometry(QtCore.QRect(80, 100, 120, 20))
        self.weather_icon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_icon_label.setObjectName("weather_icon_label")
        self.temp_output_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_output_label.setGeometry(QtCore.QRect(420, 100, 141, 16))
        self.temp_output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_output_label.setObjectName("temp_output_label")
        self.temp_output = QtWidgets.QLabel(self.centralwidget)
        self.temp_output.setGeometry(QtCore.QRect(30, 120, 256, 81))
        self.temp_output.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_output.setObjectName("temp_output")
        self.weather_icon_output = QtWidgets.QLabel(self.centralwidget)
        self.weather_icon_output.setGeometry(QtCore.QRect(40, 100, 181, 161))
        self.weather_icon_output.setText("")
        self.weather_icon_output.setObjectName("weather_icon_output")
        self.weather_icon_output.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_description_output = QtWidgets.QLabel(self.centralwidget)
        self.weather_description_output.setGeometry(QtCore.QRect(10, 230, 250, 20))
        self.weather_description_output.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_description_output.setObjectName("weather_description_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.get_button.clicked.connect(self.get_weather)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.location_selection.setItemText(0, _translate("MainWindow", "School"))
        self.location_selection.setItemText(1, _translate("MainWindow", "Home"))
        self.location_selection.setItemText(2, _translate("MainWindow", "Grandma Dawn"))
        self.location_selection.setItemText(3, _translate("MainWindow", "Grandma Nena"))
        self.location_selection.setItemText(4, _translate("MainWindow", "Grandpa Steve"))
        self.weather_icon_label.setText(_translate("MainWindow", "The weather outside"))
        self.temp_output_label.setText(_translate("MainWindow", "The temperature is"))
        # self.temp_output.setHtml(_translate("MainWindow", ""))


    def get_weather(self):
        selection = self.location_selection.currentText()
        if selection == "School":
            lat, lon = 50.9489, 5.9722
        elif selection == "Grandma Dawn":
            lat, lon = 40.8136, -96.7026
        elif selection == "Grandma Nena":
            lat, lon = 40.5070, -111.4133
        elif selection == "Grandpa Steve":
            lat, lon = 40.5853, -105.0844
        else:
            lat, lon = 51.0133, 6.0745

        API_KEY = '5e7275cf312ecbf0933795340cf9c406'
        BASE_URL = f'https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_KEY}'
        response = requests.get(BASE_URL).json()
        description = response['weather'][0]['description']
        temp_kelvin = response['main']['temp']
        temp_celsius, temp_fahrenheit = self.kelvin_to_celsius_fahrenheit(temp_kelvin)
        icon = response['weather'][0]['icon']
        icon_url = 'https://openweathermap.org/img/wn/' + icon + '@4x.png'
        image = QImage()
        image.loadFromData(requests.get(icon_url).content)
        self.weather_description_output.setText(f'There are {description} for {selection} right now!')
        self.f_temp.setText(f'{temp_fahrenheit:.2f}')
        self.c_temp.setText(f'{temp_celsius:.2f}')
        self.weather_icon_output.setPixmap(QtGui.QPixmap(image))


    def kelvin_to_celsius_fahrenheit(self, kelvin):
        celsius = kelvin - 273.15
        fahrenheit = celsius * (9 / 5) + 32
        return celsius, fahrenheit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
